name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repositorio checkout
        uses: action/checkout@v3

      - name: Configurar nodejs
        uses: action/setup-node@v3
        with:
          node-version: '18'